### ISSUE TITLE
[SourceTree] post-commit, gtm command not found

### ISSUE THREAD

**Issue by gaelfoppolo** [git-time-metric/gtm#54]
Hey,

I'm using SourceTree as GUI for my git repos but oddly `gtm` is not working.
The terminal log of ST gave me this after a closer look:

`.git/hooks/post-commit: line 7: gtm: command not found`

Here the `$PATH` when running the post-commit file from ST:

`/Applications/SourceTree.app/Contents/Resources/git_local/libexec/git-core:/Applications/SourceTree.app/Contents/Resources/bin:/Applications/SourceTree.app/Contents/Resources/git_local/bin:/Applications/SourceTree.app/Contents/Resources/git_local/gitflow:/Applications/SourceTree.app/Contents/Resources/git_local/git-lfs:/usr/bin:/bin:/usr/sbin:/sbin`

I use ZSH and it's working fine (terminal plug-in installed).

Any idea?

**Comment by mschenk42** [comment]
This appears to be a path issue when SourceTree executes git hooks.  Here's a link that talks about this [Hooks failing because of paths](https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly).

One way to fix this, is to set the path for gtm.  In your git root project directory,  edit the ` .git/hooks/post-commit` and set the path for gtm.

`/usr/local/bin/gtm commit --yes`

If you installed with brew, gtm should be in `/usr/local/bin`.

**Comment by gaelfoppolo** [comment]
Yup hard-coding the path is working.
The main problem is I have to set the path for every git project :/
A permanent fix is scheduled in a future version?

**Comment by mschenk42** [comment]
I'll see if there is way to add a configuration option for this.

**Comment by gaelfoppolo** [comment]
Awesome! 👍

**Comment by mschenk42** [comment]
fixed: https://github.com/git-time-metric/gtm/releases/tag/v1.2.5
